package system;


public enum EnumServices {
	
	//Servicos da visao pro controle
	CREATE_CUSTOMER,
	CREATE_SELLER,
	LOGIN_CUSTOMER,
	LOGIN_SELLER,
	LIST_ITENS,
	MAKE_QUESTION,
	BUY_ITEM,
	SEND_ANSWER,
	SEARCH_ITEM,
	ADD_ITEM,
	SOLD_ITEMS,
	BOUGHT_ITEMS,
	FOR_SALE_ITEMS,
	
	//Servicos do controle pro modelo
	GET_ITENS,
	GET_CUSTOMERS,
	GET_SELLERS,
	GET_ITEM,
	GET_CUSTOMER,
	GET_SELLER,
	GET_SOLD_ITENS,
	GET_BOUGHT_ITENS,
	GET_SELLER_ITENS,
	
	SAVE_ITEM,
	SAVE_CUSTOMER,
	SAVE_SELLER,
	
	MAKE_SEARCH_ITEM,
	POSSIBLE_MAKE_PURCHASE,
	MAKE_PURCHASE,
	
	// Servicos da compra de um produto
	ITEM_EXIST,
	CUSTOMER_EXIST,
	SELLER_EXIST,
	HAS_ENOUGHT_ITEM,
	HAS_ENOUGHT_FUNDS,
	
	ADD_FUNDS_SELLER,
	ADD_FUNDS_CUSTOMER,
	DEDUCE_AMOUNT_PRODUCT,
	ADD_SELL_CUSTOMER,
	ADD_SELL_SELLER,
	
	// Servicos de login
	CONFIRM_LOGIN_CUSTOMER,
	CONFIRM_LOGIN_SELLER,
	
	
	// Servicos de pergunta
	QUESTION_EXIST,	
	SAVE_QUESTION,
	SAVE_ANSWER,

	//Servicos para montagem dos subgrupos
	NEW_VIEW_MEMBER,
	NEW_CONTROL_MEMBER,
	NEW_MODEL_MEMBER,
	TRANSFER_STATE,
	
	//Servicos do sistema
	TOTAL_FUNDS_BOOL,
	TOTAL_FUNDS_INT;
			
}

